### ISSUE TITLE
support for mssql

### ISSUE THREAD

**Issue by yarivfive** [sdispater/orator#101]
Hi Guys,
I'm using eloquent with PHP Laravel and it's great.
now I'd like to use it with Python and came across your project.
I see there is no out of the box support for MS SQL. 
Is it planned to add such support in the near future?
If not, how hard would it be to add it? can I do it with your guidance? 
If I do, I will be happy to contribute it to your project

thanks and best regards
Yariv

**Comment by sdispater** [comment]
Thanks for your interest in Orator.

I don't plan on adding support for other backends, no. However, it would be fairly easy to create a new package (let's say `orator-mssql`) that does.

There are multiple things to consider when adding a new backend:

* A `Connection` class (This is the main object to execute queries)
* A `Connector` class (This is the class that wraps the DBAPI objects and handles configuration)
* A `QueryGrammar` (This is the class that formats `QueryBuilder` instructions to proper SQL)
* A `QueryProcessor` (Handles the the processing of selects results or `insert_get_id` statements)
* A `SchemaGrammar` (Formats migration statements to proper SQL)
* A `SchemaManager` (Transforms raw schema queries to known Orator objects (`Table`, `Column`, `ForeignKeyConstraint`))
* A `DatabasePlatform` (Mainly returns SQL statement to handle most DB operations (`ALTER TABLE`, `CREATE_TABLE`, etc...))
* And possibly a `SchemaBuilder`, even though it’s not necessarily required.

You can take the existing classes as an inspiration.

I added a class method on the `ConnectionFactory` class to easily register new connectors and connections. Basically, you do `ConnectionFactory.register_connection(‘db2’, DB2Connection)` and `ConnectionFactory.register_connector(‘db2’, DB2Connector)`.
Then, your `Connection` class only needs to return the proper grammar, processor, schema grammar and schema manager.

If you need any help, tell me. I know it might seem a little overwhelming but since you've used Eloquent you can also take inspiration from the PHP code.

**Comment by yarivfive** [comment]
thanks

I'm currently using sqlalchemy and it is "doing the job" 
thanks for your reply
