### ISSUE TITLE
Modify data in chunk only return half data

### ISSUE THREAD

**Issue by RustJason** [sdispater/orator#119]
```python
q = Model.where("cond1", 1).where("cond2", 2)
print q.count()
for datas in q.chunk(5):
    for data in datas:
        print data.x
        Model.where("id", data.id).update(cond2=1)

```
q.count = 10
but after update, only half of the data being updated, anyway to improve this?

**Comment by sdispater** [comment]
The problem comes the fact that you update inside the code to `chunk()`.

Each time you get a chunk from `chunk()` it executes an SQL query. Here is what happens internally:

When you get you first chunk, the following SQL query is executed

```sql
SELECT * FROM "models" WHERE "cond1" = 1 AND "cond2" = 2 LIMIT 5 OFFSET 0
```
Then, you update the five entries you just got and get another chunk with the following query:

```sql
SELECT * FROM "models" WHERE "cond1" = 1 AND "cond2" = 2 LIMIT 5 OFFSET 5
```

But at this point you already updated five entries so you will miss five entries that haven't been updated yet.
