### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by mattcl** [sdispater/orator#204]
We're re-evaluating our decision to use orator. Is this still being maintained?

**Comment by jes5e** [comment]
I was just about to post the same question! I would like to use this for a new python project, but it doesn't look like there's been a commit for 6th months. Wondering if it's actively maintained?

**Comment by jpventura** [comment]
@jes5e Seems like it is active because @sdispater recently updated [Pendulum](https://github.com/sdispater/pendulum) recently.

@mattcl, did you have any issue using [Orator](https://github.com/sdispater/orator)? I am starting the integration with other databases.

**Comment by mattcl** [comment]
@jpventura Bug-wise, in the past the maintainers were pretty responsive. We have two outstanding issues (the nested transaction issue with postgresql and the infinite recursion related to soft-deletes). We've resorted to patching these locally for now. There were also some issues regarding the way we had to think about things, particularly coming from ActiveRecord. For instance, orator doesn't handle has_many_through in the same way the ActiveRecord does.

**Comment by joaobarbosa** [comment]
@sdispater a word about it? 😅

**Comment by bingtel** [comment]
it seems not maintained.  :(

**Comment by sdispater** [comment]
Sorry for the lack of activity and input :-(

To reassure everyone: this project is not abandonned. It's just that I currently do not have a lot of time to spend on Orator. I am currently focusing my efforts on [pendulum](https://github.com/sdispater/pendulum) and its next major version before anything else.

However, I will try to triage the issues and make a bugfix release in the coming weeks. I can't give you an exact ETA since it depends on a lot of things.

Anyway, thanks for your interest in Orator :-)

**Comment by jairojair** [comment]
I'm using this project in production, It's Amazing! 

Thanks u @sdispater !

**Comment by jychen7** [comment]
> For instance, orator doesn't handle has_many_through in the same way the ActiveRecord does.

yeah, also mention at https://github.com/sdispater/orator/issues/167

**Comment by josephmancuso** [comment]
Closing because the question has been answered
