### ISSUE TITLE
Pluralization of table titles inconsistent for multiple word titles

### ISSUE THREAD

**Issue by nicholastulach** [sdispater/orator#66]
Expected: The examples in the documentation suggest that a table such as "RoleUser" should have the default database name of "roles_users".

Current: Calls to methods marked with `@has_many` result in an expected query for the table `role_users` instead of `roles_users`. See attached files.

[sample_project.zip](https://github.com/sdispater/orator/files/220972/sample_project.zip)

Try running `main.py` (I'm using Python 3.5). I've also included a sample database, which can be created by running the included SQL script (see zip file).

**Comment by nicholastulach** [comment]
If i specifically set the `__table__` in the `role_user` table to `roles_users`, then i get the following exception: 

`orator.exceptions.query.QueryException: (1054, "Unknown column 'addresses.roles_user_id' in 'on clause'") (SQL: SELECT `addresses`.*, `roles_users`.`user_id` FROM `addresses` INNER JOIN `roles_users` ON `roles_users`.`id` = `addresses`.`roles_user_id` WHERE `roles_users`.`user_id` = %s ([1]))`

**Comment by sdispater** [comment]
This is the expected behavior : the `@has_many` or `@has_many_through` are not meant to be used with many to many relationships. They look for the pluralized name of the underscored name of the model (`role_users`), and only `@belongs_to_many` will look for `roles_users`.

However, if you look at the documentation (https://orator-orm.com/docs/0.8/orm.html#hasmanythrough), you can notice that `@has_many_through` accepts arguments to specify the keys to use. So if you want, addresses to be accessible to a user through the `roles_users` table, you need to specify the `__table__` attribute on the `RoleUser` model and the `addresses` relationship should look like this:

```python
@has_many_through(RoleUser, 'id', 'roles_users_id')
def addresses(self):
    return Address
```
