### ISSUE TITLE
Why use "ON UPDATE CURRENT_TIMESTAMP" clause for created_at column but not for updated_at column?

### ISSUE THREAD

**Issue by Peilun0912** [sdispater/orator#90]
From the names, I think the `updated_at` column is supposed to be the one updated when the row updated, not the `created_at` column. It confuses me.

**Comment by sdispater** [comment]
What is the backend you are using and which version ?

Also, could you provide a code sample that causes the issue?

**Comment by Peilun0912** [comment]
I'm using MariaDB 10.0.24.

My code is simple. I just create a migration as below and run `orator migrate` command.

```python
from orator.migrations import Migration


class CreateSmsGroupsTable(Migration):

    def up(self):
        """
        Run the migrations.
        """
        with self.schema.create('sms_groups') as table:
            table.increments('id')
            table.string('name')
            table.timestamps()

    def down(self):
        """
        Revert the migrations.
        """
        self.schema.drop('sms_groups')
```

The created table has the `created_at` column which is set `NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` and the `updated_at` column which is set `NOT NULL DEFAULT '0000-00-00 00:00:00'`.

**Comment by sdispater** [comment]
The error is due to how MySQL or MariaDB is configured, especially the `explicit_defaults_for_timestamp` option that is disabled by default on MySQL < 5.6.5 and I assume MariaDB:

> at most one TIMESTAMP column per table could be automatically initialized or updated to the current date and time.

So, basically the first NOT NULL TIMESTAMP column will get the `NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`.

You might want to try doing:

```python
table.timestamps(use_current=True)
```

which will be the default in the next version and generate the following SQL for MariaDB and MySQL <= 5.6 that have the configuration option disabled:

```sql
`created_at` TIMESTAMP DEFAULT 0 NOT NULL,
`updated_at` TIMESTAMP DEFAULT 0 NOT NULL
```
and otherwise, it will generate:

```sql
`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
```

**Comment by Peilun0912** [comment]
Tested. Now both two columns are set in the same way. Thanks for the solution!
